### ISSUE TITLE
Break up StringExtensions into multiple files to reduce size and merge conflicts

### ISSUE THREAD

**Issue by ardalis** [ardalis/Ardalis.Extensions#13]

**Comment by josuave** [comment]
Would breaking the extensions down to functional namespaces make sense? I was thinking "Ardalis.Extensions.Parsing" and "Ardalis.Extensions.Conversions". I'll have a PR shortly with these changes.

**Comment by ardalis** [comment]
I've decided one method per file (or multiple if they are overloads) using partials is the way.

**Comment by josuave** [comment]
Got it.

**Comment by ardalis** [comment]
Fixed by #32
