### ISSUE TITLE
Math Extensions

### ISSUE THREAD

**Issue by josuave** [ardalis/Ardalis.Extensions#39]
A set of extension methods should be made for numeric types that provide mathematic operations.

- [x] Addition
- [x] Subtraction
- [x] Multiplication
- [x] Division
- [x] Modulus
- [x] Powers

Others?

**Comment by ardalis** [comment]
Syntax like:
int x = 2;
int result = x.Add(3);
result = result.Times(4);
result = result.Minus(6);
result = result.DividedBy(2);

**Comment by josuave** [comment]
I agree. Ill start contributing shortly.

**Comment by josuave** [comment]
All the original items are currently covered. We can either add more or complete this issue.

**Comment by ardalis** [comment]
I'll close it, thanks.
